# Generated by Django 5.2.7 on 2025-11-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_courier_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
