# Generated by Django 5.2.7 on 2025-12-17 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productcategory_quickrestoorder_quickrestoproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickRestoMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickresto_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category_name', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quickrestoorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='quickrestoorder',
            old_name='qr_id',
            new_name='quickresto_id',
        ),
        migrations.RenameField(
            model_name='quickrestoproduct',
            old_name='qr_id',
            new_name='quickresto_id',
        ),
        migrations.RemoveField(
            model_name='quickrestoorder',
            name='items',
        ),
        migrations.AddField(
            model_name='quickrestoorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quickrestoorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quickrestoorder',
            name='quickresto_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quickrestoorder',
            name='table_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quickrestoorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Создан'), ('COOKING', 'Готовится'), ('DELIVERY', 'В пути'), ('DONE', 'Доставлен')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='quickrestoorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('cooking', 'Готовится'), ('ready', 'Готов'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quickrestoproduct',
            name='category',
            field=models.CharField(blank=True, default='Без категории', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='min_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
